"""
Django settings for gateway_service project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------------
import os
from dotenv import load_dotenv

load_dotenv()
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
MODE = os.environ['MODE']
ALLOWED_HOSTS = os.environ['DJANGO_ALLOWED_HOSTS'].split(',')

CAR_SERVICE_URL = os.getenv("CAR_SERVICE_URL", "http://car-service:8000/api/v1")
RENTAL_SERVICE_URL = os.getenv("RENTAL_SERVICE_URL", "http://rental-service:8000/api/v1")
PAYMENT_SERVICE_URL = os.getenv("PAYMENT_SERVICE_URL", "http://payment-service:8000/api/v1")

# REDIS_URL = os.environ.get("REDIS_URL", "redis://redis:6379/0")  # Redis disabled

# JWT validation against IdP JWKs.
IDP_ISSUER = os.environ.get('IDP_ISSUER', 'http://identity-provider:8000')
IDP_JWKS_URI = os.environ.get('IDP_JWKS_URI', f"{IDP_ISSUER.rstrip('/')}/api/v1/jwks")
IDP_AUDIENCE = os.environ.get('IDP_AUDIENCE', 'spa')
IDP_JWKS_TTL = int(os.environ.get('IDP_JWKS_TTL', '600'))

# Kafka producer (rental-events).
KAFKA_BOOTSTRAP = os.environ.get('KAFKA_BOOTSTRAP', 'kafka:9092')
KAFKA_TOPIC = os.environ.get('KAFKA_TOPIC', 'rental-events')
KAFKA_CLIENT_ID = os.environ.get('KAFKA_CLIENT_ID', 'gateway-service')

# Statistics service (proxy target).
STATISTICS_SERVICE_URL = os.environ.get(
    'STATISTICS_SERVICE_URL',
    'http://statistics-service:8000/api/v1',
)

# Если запускаем локально, то соответствующий хост
if MODE == 'local':
    DEBUG = True
else:
    DEBUG = False

# Куда собирать статику командой collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"

ASGI_APPLICATION = "gateway_service.asgi.application"  # опционально

# Database
DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "testdb.sqlite3"),

    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "standard": {
            "format": "[%(asctime)s] %(levelname)s %(name)s: %(message)s",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        }
    },

    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },

        "gateway_service.gateway": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# --------------------------------------------------------------------------


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # для api
    'corsheaders',
    'rest_framework',
    # регистрация приложений
    "gateway_service.gateway.apps.GatewayConfig",
]

CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get('GATEWAY_CORS_ORIGINS', '').split(',') if o.strip()
]
CORS_ALLOW_HEADERS = list({'authorization', 'content-type', 'accept'})

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'authlib.middleware.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'authlib.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gateway_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gateway_service.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
