# Generated by Django 5.2.5 on 2025-11-13 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_uid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('username', models.CharField(max_length=80)),
                ('payment_uid', models.UUIDField()),
                ('car_uid', models.UUIDField()),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], default='IN_PROGRESS', max_length=20)),
            ],
            options={
                'db_table': 'rental',
                'indexes': [models.Index(fields=['rental_uid'], name='rental_rental__23a50d_idx'), models.Index(fields=['username'], name='rental_usernam_15809a_idx'), models.Index(fields=['status'], name='rental_status_02be4a_idx')],
            },
        ),
    ]
