fullnameOverride: statistics-consumer

image:
  repository: ghcr.io/CHANGE-ME/statistics-service   # same image
  tag: latest

replicaCount: 1

service:
  enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false

extraConfigMap:
  enabled: true
  data:
    DJANGO_SECRET_KEY: "k8s-change-me"
    MODE: "docker"
    DJANGO_ALLOWED_HOSTS: "*"
    DB_STATISTICS: "statistics"
    DB_USER: "program"
    DB_DOCKER_HOST: "postgres"
    DB_LOCAL_HOST: "localhost"
    DB_PORT: "5432"
    ROLE: "consumer"
    KAFKA_BOOTSTRAP: "rsoi-kafka:9092"
    KAFKA_TOPIC: "rental-events"
    KAFKA_CONSUMER_GROUP: "statistics-service-cg"
    KAFKA_AUTO_OFFSET_RESET: "earliest"

env:
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-credentials
        key: APP_DB_PASSWORD
