fullnameOverride: statistics-service

image:
  repository: ghcr.io/CHANGE-ME/statistics-service
  tag: latest

replicaCount: 1

extraConfigMap:
  enabled: true
  data:
    DJANGO_SECRET_KEY: "k8s-change-me"
    MODE: "docker"
    DJANGO_ALLOWED_HOSTS: "*"
    DB_STATISTICS: "statistics"
    DB_USER: "program"
    DB_DOCKER_HOST: "postgres.rsoi-data"
    DB_LOCAL_HOST: "localhost"
    DB_PORT: "5432"
    ROLE: "web"
    IDP_ISSUER: "https://id.example.com"
    IDP_JWKS_URI: "http://identity-provider:8000/api/v1/jwks"
    IDP_AUDIENCE: "spa"
    KAFKA_BOOTSTRAP: "rsoi-kafka.rsoi-data:9092"
    KAFKA_TOPIC: "rental-events"
    KAFKA_CONSUMER_GROUP: "statistics-service-cg"

env:
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-credentials
        key: APP_DB_PASSWORD
