# Generated by Django 5.2.5 on 2025-11-13 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_uid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('CANCELED', 'Canceled')], default='PAID', max_length=20)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'payment',
                'indexes': [models.Index(fields=['payment_uid'], name='payment_payment_30844c_idx'), models.Index(fields=['status'], name='payment_status_1c1ab2_idx')],
            },
        ),
    ]
