# Generated by Django 5.2.5 on 2026-05-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('username', models.CharField(blank=True, default='', max_length=80)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'eventlog',
                'ordering': ('-timestamp',),
            },
        ),
    ]
