# Generated by Django 5.2.5 on 2025-10-25 09:26

import uuid
from django.db import migrations, models

def add_initial_car(apps, schema_editor):
    Car = apps.get_model('cars', 'Car')
    Car.objects.create(
        id=1,
        car_uid="109b42f3-198d-4c89-9276-a7520a7120ab",
        brand="Mercedes Benz",
        model="GLA 250",
        registration_number="ЛО777Х799",
        power=249,
        price=3500,
        type="SEDAN",
        availability=True,
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_uid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('registration_number', models.CharField(max_length=20)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('MINIVAN', 'Minivan'), ('ROADSTER', 'Roadster')], max_length=20)),
                ('availability', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cars',
                'indexes': [models.Index(fields=['availability'], name='cars_availab_ce8337_idx'), models.Index(fields=['brand', 'model'], name='cars_brand_78f303_idx')],
            },
        ),
        migrations.RunPython(add_initial_car, migrations.RunPython.noop),
    ]
